apiVersion: v1
kind: Service
metadata:
  name: gitea-clusterip
  namespace: gitea
  labels:
    app: gitea
spec:
  ports:
    - name: gitea-web
      port: 3000
      protocol: TCP
      targetPort: 3000
    - name: gitea-ssh
      port: 22
      protocol: TCP
      targetPort: 22
  selector:
    app: gitea-app
    type: ClusterIP
      # clusterIP: 10.96.0.10