apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: gitea
  name: gitea-lb
spec:
  ports:
  - name: port-1
    port: 3000
    protocol: TCP
    targetPort: 3000
  - name: port-2
    port: 22
    protocol: TCP
    targetPort: 22
  selector:
    app: gitea-app
  type: LoadBalancer