version: "3"

networks:
  gitea:
    external: false

services:
  server:
    image: gitea/gitea:1.21.4
    container_name: gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - APP_NAME=Dhruv's code hub
      - DISABLE_REGISTRATION=true
      - DEFAULT_USER_VISIBILITY=private
      - DEFAULT_ORG_VISIBILITY=private
      - DOMAIN=git.typdef.com
      - ROOT_URL=https://git.typdef.com
    restart: always
    networks:
      - gitea
    volumes:
      - /var/lib/gitea/data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "7920:3000"
      - "7922:22"
